// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ksebcddytwztdjymswow.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtzZWJjZGR5dHd6dGRqeW1zd293Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyMzM4MDksImV4cCI6MjA2ODgwOTgwOX0.B65gyVa2JoLkM1wml0szab0bkpsQ7kciuY0UuqJKAY0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});